apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: startup-http
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    args:
    - liveness

    ports:
    - name: liveness-port
      containerPort: 8080

    livenessProbe:
      httpGet:
        path: /started
        port: liveness-port
      failureThreshold: 1
      periodSeconds: 10

    startupProbe:
      httpGet:
        path: /started
        port: liveness-port
      failureThreshold: 30
      periodSeconds: 10
