apiVersion: v1
kind: PersistentVolume
metadata:
  name: www-web-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-storage-class
  hostPath: # Use this for local storage, change as needed for your environment
    path: /mnt/data/nginx
