apiVersion: v1
kind: Service
metadata:
  name: deployment-svc
  labels:
    app: pbitty-deployment
spec:
  type: NodePort
  selector:
    app: pbitty-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
