apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: default
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:4.7.3-apache
        resources: {}
        volumeMounts:
        - name: sql-volume
          mountPath: /etc/secret-data
        ports:
        - containerPort: 80
      volumes:
      - name: sql-volume
        secret:
          secretName: my-file-password
